services:
  mongodb:
    image: mongo:7
    container_name: otcs-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - otcs-mongo-data:/data/db

volumes:
  otcs-mongo-data:
